### ISSUE TITLE
ModuleNotFoundError: No module named 'clip'

### ISSUE THREAD

**Issue by yliu-cs** [deepmind/dmvr#7]
I tried to run [vatt](https://github.com/google-research/google-research/tree/master/vatt) source code that relies on dmvr, but it shows:

```
Traceback (most recent call last):
  File "/home/yliu/.conda/envs/vatt/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/yliu/.conda/envs/vatt/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/yliu/work/yliu/VHD/baseline/google-research/vatt/main.py", line 25, in <module>
    from vatt.experiments import finetune
  File "/home/yliu/work/yliu/VHD/baseline/google-research/vatt/experiments/finetune.py", line 22, in <module>
    from vatt.data import dataloaders
  File "/home/yliu/work/yliu/VHD/baseline/google-research/vatt/data/dataloaders.py", line 23, in <module>
    from vatt.data import loading
  File "/home/yliu/work/yliu/VHD/baseline/google-research/vatt/data/loading.py", line 28, in <module>
    from vatt.data import processing
  File "/home/yliu/work/yliu/VHD/baseline/google-research/vatt/data/processing.py", line 22, in <module>
    from dmvr import modalities
  File "/home/yliu/.conda/envs/vatt/lib/python3.9/site-packages/dmvr-0.0.1-py3.9.egg/dmvr/modalities.py", line 23, in <module>
    from dmvr import processors
  File "/home/yliu/.conda/envs/vatt/lib/python3.9/site-packages/dmvr-0.0.1-py3.9.egg/dmvr/processors.py", line 20, in <module>
    from dmvr import tokenizers
  File "/home/yliu/.conda/envs/vatt/lib/python3.9/site-packages/dmvr-0.0.1-py3.9.egg/dmvr/tokenizers.py", line 19, in <module>
    import clip.simple_tokenizer
ModuleNotFoundError: No module named 'clip'
```

Which package does the `clip` module depend on?

python version: `Python 3.9.15`

pip list:

```
Package                      Version
---------------------------- ----------
absl-py                      1.3.0
astunparse                   1.6.3
cachetools                   5.2.0
certifi                      2022.9.24
charset-normalizer           2.1.1
cloudpickle                  2.2.0
decorator                    5.1.1
dm-tree                      0.1.7
dmvr                         0.0.1
flatbuffers                  2.0.7
gast                         0.4.0
google-auth                  2.15.0
google-auth-oauthlib         0.4.6
google-pasta                 0.2.0
grpcio                       1.51.1
h5py                         3.7.0
idna                         3.4
imageio                      2.22.4
importlib-metadata           5.1.0
joblib                       1.2.0
keras                        2.7.0
Keras-Preprocessing          1.1.2
libclang                     14.0.6
Markdown                     3.4.1
MarkupSafe                   2.1.1
networkx                     2.8.8
numpy                        1.24.0rc2
oauthlib                     3.2.2
opt-einsum                   3.3.0
packaging                    22.0
Pillow                       9.3.0
pip                          22.3.1
protobuf                     3.19.6
pyasn1                       0.5.0rc2
pyasn1-modules               0.3.0rc1
PyWavelets                   1.4.1
PyYAML                       6.0
requests                     2.28.1
requests-oauthlib            1.3.1
rsa                          4.9
scikit-image                 0.19.3
scikit-learn                 1.2.0
scipy                        1.9.3
sentencepiece                0.1.97
setuptools                   65.5.0
six                          1.16.0
tensorboard                  2.11.0
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.1
tensorflow                   2.7.0
tensorflow-addons            0.15.0
tensorflow-estimator         2.7.0
tensorflow-hub               0.12.0
tensorflow-io-gcs-filesystem 0.28.0
tensorflow-probability       0.15.0
tensorflow-text              2.7.0
termcolor                    2.1.1
threadpoolctl                3.1.0
tifffile                     2022.10.10
typeguard                    2.13.3
typing_extensions            4.4.0
urllib3                      1.26.13
Werkzeug                     2.2.2
wheel                        0.37.1
wrapt                        1.14.1
zipp                         3.11.0
```

Thank you😊

**Comment by yliu-cs** [comment]
When I install the [CLIP](https://github.com/openai/CLIP) the code works fine, I'm not sure if this is correct.
Please provide the correct boot in [README.md](https://github.com/deepmind/dmvr/blob/master/README.md) or [requirements.txt](https://github.com/deepmind/dmvr/blob/master/requirements.txt).

**Comment by Tenglon** [comment]
yliu-cs's solution works for me.
